openapi: 3.0.1
info:
  title: monster-lammasu
  x-cortex-tag: monster-lammasu
  x-cortex-custom-metadata:
    alignment: lawful-good
    type: fiend
    challenge_rating: 4
    legendary: false
    armor_class: 17
    hit_points: 167
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-lammasu
      alias: github-token-test
